[project]
name = "Medical-Policy"
version = "0.1.0"
description = "Policy Chat Assistant with Google Gemini and LangChain"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.48.0",
    "langchain>=0.3.27",
    "langchain-google-genai>=2.0.10",
]
