[project]
name = "Medical-Policy"
version = "0.1.0"
description = "Policy Chat Assistant with Google Gemini"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.48.0",
    "google-genai>=1.24.0",
    "httpx>=0.24.0",
    "pydantic>=2.0.0"
]
